loopandlearn/LoopFollow

- LoopFollow/Controllers/AppStateController.swift
- LoopFollow/Controllers/Stats.swift
- LoopFollow/Controllers/StatsView.swift
- LoopFollow/ViewControllers/GeneralSettingsViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/repository/UserDefaults.swift
New setting for IFCC A1C
Default false
Toggling updates the stats view.
IFCC A1C can be used regardless of unit (mg/dl - mmol/L)
> setting to use useIFCC A1C

- LoopFollow/Controllers/AppStateController.swift
- LoopFollow/Controllers/Graphs.swift
- LoopFollow/Controllers/NightScout.swift
- LoopFollow/Controllers/StatsView.swift
- LoopFollow/Controllers/Timers.swift
- LoopFollow/ViewControllers/AdvancedSettingsViewController.swift
- LoopFollow/ViewControllers/GraphSettingsViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/helpers/DataStructs.swift
- LoopFollow/helpers/DateTime.swift
- LoopFollow/repository/UserDefaults.swift
- Pods/ShareClient/ShareClient/ShareClient.swift
Adding an ability to show more than 1 day of data in the chart.
Nightscout API by default supports up to 4 days of history. If both Dexcom share and Nightscout are configured, first 24 hrs are loaded from Dexcom and the remainder from Nightscout.
Also adding a setting to show vertical lines at midnight: convenient when looking at multiple days of data.
> Show more than 1 day of data in the chart

- LoopFollow/Loop Follow.entitlements
- fastlane/Fastfile
App Groups are not used in this project, and can be removed for a simplified Fastlane cloud build setup.
> Remove App Groups from LoopFollow target, and app group capabilities from Fastfile

- LoopFollow/Application/SceneDelegate.swift
- LoopFollow/ViewControllers/GeneralSettingsViewController.swift
Now you can easily toggle the "Speak BG" feature on and off directly from your home screen! I've added a Home Screen Quick Action that lets you control the feature with just a 3D touch on the LoopFollow app icon.
- Home Screen Quick Action: Quickly toggle "Speak BG" without going through the settings screens.
- Synced Settings: The switch in General Settings and the Quick Action are in sync.
- Audible Confirmation: Get instant feedback when you toggle the feature using the Quick Action.
> Home Screen Quick Action for Speak BG

- LoopFollow/Controllers/NightScout.swift
Loop 3 may upload duplicate svg entries, which can cause issues with LoopFollow's graphs and statistics. This issue may also arise when both bridge is enabled in Nightscout and Loop 'upload readings' are used. This pr resolves the issue by filtering out one reading every five minutes.
> Duplicate blood glucose entries

- LoopFollow/Controllers/Timers.swift
- LoopFollow/ViewControllers/MainViewController.swift
This PR introduces a pull-down-to-refresh feature, with the pull-down action implemented on the BG value text. This design choice was made because other controls in the app already involve pulling and scrolling actions. When a refresh is initiated, the feature updates all values by invalidating and resetting all timers, which in turn triggers the download of new data.
Resolves #5
> pull-to-refresh

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Controllers/NightScout.swift
- LoopFollow/ViewControllers/SettingsViewController.swift
- LoopFollow/helpers/NightscoutUtils.swift
This pull request adds URL and token validation for Nightscout settings to improve user experience and provide clear error messages when the user enters incorrect or unreachable URLs and tokens. 
The changes include:
* Implementing a verifyURLAndToken function in a new NightscoutUtils class to check the validity of the user-entered URL and token by making a request to the Nightscout server.
* Adding various error cases to handle empty addresses, invalid URLs, network errors, site not found errors, invalid tokens, token requirements, and unknown errors.
* Updating the SettingsViewController to call the verifyURLAndToken function when the user enters or changes the URL or token, and updating the status label with appropriate error messages or an "OK" status when the URL and token are valid. …
> Add Nightscout URL and token validation to Settings

- LoopFollow.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- LoopFollow.xcworkspace/xcshareddata/xcschemes/LoopFollow.xcscheme
This pull request updates the WorkspaceSettings.xcsettings file within the LoopFollow.xcworkspace to set the default scheme to LoopFollow. This change will make it more convenient for new users by automatically selecting the LoopFollow scheme when opening the project for the first time. As a result, this will also help avoid build errors and reduce the number of queries in forums related to scheme selection.
Note:
This setting only affects the default scheme selection when opening the workspace for the first time. Once a user selects a different scheme, Xcode will remember their preference for future sessions.
> Set default scheme to LoopFollow in workspace settings

- BuildLoopFollow.sh
- Config.xcconfig
- LoopFollow.xcodeproj/project.pbxproj
This pull request adds automatic signing of Loop Follow (LF) without making changes to loopnlearn/LoopBuildScripts. However, considering the likelihood of merging these scripts in the future, I have aligned the LF implementation with loopnlearn/LoopBuildScripts by borrowing relevant parts of build_functions.sh. This is done to maintain code standard and improve user experience consistency.
PR Walkthrough:
- The LF project now uses the LF_DEVELOPMENT_TEAM variable to set the team ID.
- LF Config.xcconfig includes a global config file "../../LoopFollowConfigOverride.xcconfig" to persistently store the team ID.
- The LF build script accepts two optional parameters, repo and branch, for simplified testing. Usage example: `/bin/bash -c "$(curl -fsSL …
> Add Automatic Signing for Loop Follow and Align Scripts with loopnlearn/LoopBuildScripts

- LoopFollow/Controllers/Alarms.swift
- LoopFollow/Controllers/NightScout.swift
- LoopFollow/ViewControllers/AlarmViewController.swift
- LoopFollow/ViewControllers/SnoozeViewController.swift
- LoopFollow/repository/UserDefaults.swift
This pull request introduces a new low battery alarm feature to LoopFollow. The feature triggers an alarm when the Loop phone battery level falls below a user-specified threshold. This enhancement is aimed at ensuring that users can take timely action to recharge their device's battery, thereby maintaining uninterrupted functioning of Loop.
Changes include:
- A new setting that allows users to specify the battery level at which the alarm should be triggered.
- A mechanism to monitor the device's battery level and trigger an alarm when the level falls below the specified threshold.
- A Snooze functionality for the battery alarm, along with customizable snooze duration.
Looking forward to your feedback on this new feature.
> Low Battery Alarm

- LoopFollow/Controllers/NightScout.swift
- LoopFollow/Extensions/ShareClientExtension.swift
Summary
This pull request includes enhancements to the sgv JSON decoding process to provide more robust error handling and flexibility in how we treat incoming data.
Changes in NightScout.swift
I have wrapped the JSON decoding operation in a do-catch block to better handle any potential decoding errors. Now, rather than merely attempting to decode and potentially failing silently, the application will now provide specific feedback about the nature of any encountered decoding error. This includes data corruption, missing keys, missing values, and type mismatches. This should aid in diagnosing problems with incoming JSON data.
Changes in ShareClientExtension.swift
I've also refined the ShareGlucoseData structure to better handle variations in incoming data.
The sgv property now accepts both …
>  Improve JSON Decoding in NightScout.swift and ShareClientExtension.swift

- LoopFollow/Controllers/NightScout.swift
This PR addresses a potential issue in the processing of basal data where the `duration` field might not be present or could be null. By using optional chaining and the nil-coalescing operator, we provide a default value of `0.0` for such cases. This makes the code more resilient to unexpected or malformed data. 
The specific line of code being modified is: 
let priorDuration = priorEntry?["duration"] as? Double ?? 0.0
This change ensures that if `duration` is not available in the `priorEntry`, it will default to `0.0`, preventing any runtime crashes due to unwrapping a nil value. This approach provides a more robust and fail-safe mechanism to handle the optional duration.
Importantly, this code change has been tested by the user who originally encountered this issue and confirmed as …
> Handling Optional Duration in Basal Data Processing

- Gemfile.lock
jmespath upgrade based on dependabot security warning
> jmespath update

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Application/AppDelegate.swift
- LoopFollow/Extensions/EKEventStore+Extensions.swift
- LoopFollow/Info.plist
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/ViewControllers/WatchSettingsViewController.swift
This will build with lower versions of xcode since there is a compile time swift version check
Calendar access control is moved centrally to an extension
If the app is missing access, this is now displayed in the apple watch/calendar menu
Calendar access is changed to follow: https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels
> Preparation for ios17 calendar access

- LoopFollow/Controllers/NightScout.swift
A fix for the issue where user get a 4000 value that messes up the graph and statistics when starting a G7 the first time.
> Filter out values above 600

- LoopFollow/Info.plist
This allows to open Loop Follow via the url loopfollow://
This can be handy for instance if using Scriptable to make a widget on the iPhone lockscreen or elsewhere.
To enable this, select
"When interacting" = Open URL
"URL" = loopfollow://
> Add "loopfollow" CFBundleURLSchemes

- .github/workflows/add_identifiers.yml
- .github/workflows/build_LoopFollow.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
- fastlane/Fastfile
This pull requests migrates improvements relating to browser build validation brought to `LoopKit/LoopWorkspace` `dev` with [PR77](https://github.com/LoopKit/LoopWorkspace/pull/77) and [PR86](https://github.com/LoopKit/LoopWorkspace/pull/86). Thanks to @billybooth for the fruitful collab.
> Migrate Validation Improvements from LoopKit/LoopWorkspace

- LoopFollow/Controllers/Graphs.swift
- LoopFollow/Controllers/NightScout.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/ViewControllers/SettingsViewController.swift
- LoopFollow/repository/UserDefaults.swift
- Auto detection of iAPS devicestatus vs Loop
- A new info table category "Autosens" was added.
- infoTable.rowHeight changed from 24 to 21.
- Carbs today is now based on created_at instead of timestamp to fit iAPS
- Ensured that infoVisible values have the correct default settings and length. This fixes a bug that made LF crash for some users at rebuilding.
- The title of a switch for downloading data was updated from "Download Loop/FreeAPS Data" to "Download Loop/iAPS Data".
Many changes are copied/inspired from/by this fork: https://github.com/aug0211/aug0211-LoopFollowFAX/tree/fax
> iAPS support for LoopFollow

- .gitignore
- Config.xcconfig
- copied from iAPS
- includes LoopFollowConfigOverride.xcconfig in .gitignore
- adds the LoopFollowConfigOverride.xcconfig file to the LoopFollow project
Avoids that git tracks changes to DS_store and xcuserdata etc.
> Add .gitignore to LoopFollow

- LoopFollow/Controllers/NightScout.swift
Only the last override is allowed to run without a duration.
> fix for override without duration

- LoopFollow/Controllers/Nightscout/SAge.swift
- LoopFollow/helpers/DateTime.swift
LoopFollow does not display SAGE values of more than 10 days. That was fine when everyone was using factory G6 transmitters, which cut the session at ten days sharp. Today, many are using Anubis transmitters which allow (theoretically) running sensors up to 60 days. 
This PR changes the ten day limit into a sixty days limit. 
I have not changed anything related to Sensor change reminders, which still assume ten days is the max, and allows alerts  to be set a user defined number of hours before the ten day limit. In my view, this is fine.
> Sage>10days

- LoopFollow/Controllers/Graphs.swift
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/Controllers/Nightscout/Treatments/Basals.swift
When starting LoopFollow there would be a line down to 0 from the last bg value.
This has now been fixed. Along with some minor code cleanup related to bgchart.
> Bgchart fix for initial display

- Config.xcconfig
- LoopFollow.xcodeproj/project.pbxproj
- LoopFollowDisplayNameConfig.xcconfig
- LoopFollowInstanceConfig.xcconfig
Move app instance configuration to a separate file to avoid merge issues when updating version.
> LoopFollowInstanceConfig

- .github/workflows/add_identifiers.yml
- .github/workflows/build_LoopFollow.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
Adding a step to workflow jobs that interface Apple servers, as a workaround for build issues caused by runner clocks being out of sync. See https://github.com/actions/runner issue number 2996 for details.
name: Sync clock
run: sudo sntp -sS time.windows.com
Added to the following workflows / jobs:
validate_secrets.yml / validate-fastlane-secrets
add_identifiers.yml / identifiers
build_LoopFollow.yml / build
create_certs.yml / certificates
> Sync the GitHub runner clock with the Windows time server

- LoopFollow/Controllers/AppStateController.swift
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/ViewControllers/GeneralSettingsViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/repository/UserDefaults.swift
This pull request introduces a new feature that dynamically updates the server text based on user preferences. Key changes include:
New Functionality:
Added updateServerText function in BGData.swift for dynamic text updates in the main view controller.
User Setting Integration:
Integrated a new user setting showAppName in GeneralSettingsViewController.swift and UserDefaults.swift for toggling the display of the app's name.
Enum Extension:
Extended GeneralSettingsChangeEnum in AppStateController.swift to include showAppNameChange.
UI and Logic Updates:
Updated MainViewController.swift to use the new updateServerText function and handle the showAppNameChange setting.
Immediate Effect of Toggle:
If showAppName is toggled on, it will be immediately reflected in the GUI. When toggled off, …
> Implement Dynamic Server Text Update & Add 'Show App Name' Setting

- LoopFollow/ViewControllers/SettingsViewController.swift
This update involves setting autocapitalizationType to .none for each text field, thereby disabling automatic capitalization when a user starts typing. The change is aimed at improving user input experience, especially for fields where automatic capitalization is not necessary or could be problematic, like URLs, tokens, usernames, and passwords. The change is systematically applied in the .cellSetup closure for multiple text fields, complementing the existing autocorrectionType = .no setting.
> Disable Auto-Capitalization in Text Fields of SettingsViewController

- LoopFollow/Controllers/Alarms.swift
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/ViewControllers/MainViewController.swift
Examine indexing into .sgv and fix cases that might have an out-of-bounds fault.
Found a few more than indicated in Issue #251
> Protect against crash from index out of bounds

- LoopFollow/Controllers/NightScout.swift
- LoopFollow/Controllers/Nightscout/Profile.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/repository/UserDefaults.swift
> Display profile in infotables

- LoopFollow/Controllers/Nightscout/Treatments.swift
This pull request addresses a critical issue where the application could crash if an `eventType` was missing in any of the entries processed by the `updateTreatments` function. By implementing a guard statement to check for the presence of `eventType`, we ensure the function safely skips any entries lacking this essential piece of data.
- Added a guard statement in `updateTreatments` to check for the presence of `eventType` in each entry.
- Entries without an `eventType` are now safely ignored, preventing potential crashes.
- Tested with a dataset containing a mix of entries with and without `eventType` to ensure that the function behaves as expected.
- Confirmed that entries missing `eventType` are skipped without causing crashes, while valid entries continue to be processed correctly. …
> Fix: Prevent crash by handling missing eventType in updateTreatments

- LoopFollow/ViewControllers/NightScoutViewController.swift
**Issue**
When applying any kind of code changes in Nightscout, the web cache in Loop Follow tends to keep the old version in cache for a long time. 
There is currently no easy way to clear the web cache to make changes in nightscout visible immediately (other than to delete and reinstall Loop Follow, or wait for an extended period of time (weeks?) until the cache clears automatically)
The everyday user of LF probably dont have any needs to frequently clear the web cache, but for developers and other "super users" the inability to clear the web cache are more troublesome.
**Suggested solution**
This PR introduces an easy way to clear the nightscout web cache by extending the current function reloadWebView to also clear web cache when swiping down.
One potential UX issue with clearing the …
> Add function to clear web cache (Nightscout) when refreshing view by swiping down

- LoopFollow/Application/Base.lproj/Main.storyboard
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/Controllers/Timers.swift
- LoopFollow/ViewControllers/MainViewController.swift
Start with changes from PR #263. Then add more improvements.
* add strikethrough to font with glucose is stale (>12 minutes, 720 second).
> Snoozer improvements

- BuildDetails.plist
- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/ViewControllers/SettingsViewController.swift
- LoopFollow/helpers/BuildDetails.swift
- Scripts/capture-build-details.sh
This PR introduces enhancements to how the app manages and utilizes build information, with a particular focus on distinguishing between Xcode and TestFlight builds. A key part of this enhancement is the inclusion of a manually added `BuildDetails.plist` file in the project, which stores essential build details. The PR also includes updates to the app's logic to read from this plist and calculate build expiration dates, especially for TestFlight builds, where a specific validity period is important for managing updates and functionality.
- **Manually Added `BuildDetails.plist`**: `BuildDetails.plist` has been manually added to the project. It should be updated as needed to reflect current build details.
- **Build Expiration Logic**: The `SettingsViewController` now includes updated logic …
> Testflight build expiration

- LoopFollow/helpers/NightscoutUtils.swift
This PR addresses a bug where the date parsing in `NightscoutUtils` fails when the device is set to a 12-hour time format. The issue stems from the `DateFormatter` not being explicitly set to a locale that supports 24-hour time formats, which can lead to inconsistencies based on the user's device settings.
- Set the locale of `dateFormatterWithMilliseconds` and `dateFormatterWithoutMilliseconds` in `NightscoutUtils.parseDate` to `en_US_POSIX`. This locale is designed for machine-readable strings and ensures that the date parsing behavior is consistent, regardless of the user's regional and time format settings.
> Fix date parsing issue for 12/24-hour formats

- LoopFollow/ViewControllers/SettingsViewController.swift
- Scripts/capture-build-details.sh
- **Conditional Expiration:** Now hides the expiration section for Mac Catalyst builds, since they are not relevant.
> Mac catalyst no expiration msg

- LoopFollow/Controllers/Alarms.swift
- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
- LoopFollow/ViewControllers/AlarmViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
This PR introduces an update to the UI to indicate when Loop/iAPS is 'Not Looping'. The `LoopStatusLabel` is now dynamically updated to expand and fill the entire area designated for loop status messages when no recent loop activity has been confirmed.
- Added `evaluateNotLooping` function to determine the 'Not Looping' status.
- UI updates to `LoopStatusLabel` to cover the entire `UIStackView` when not looping.
- `PredictionLabel` is hidden when 'Not Looping' status is active.
The changes have been tested to ensure the label updates correctly and the 'Not Looping' status is clear and visible.
> Add UI update for 'Not Looping' status indication

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Controllers/Nightscout/Treatments/BGCheck.swift
- LoopFollow/Controllers/Stats.swift
- LoopFollow/Extensions/ShareClientExtension.swift
- LoopFollow/helpers/GlucoseConversion.swift
- LoopFollow/helpers/NightscoutUtils.swift
- LoopFollow/helpers/bgUnits.swift
This PR introduces the display of manual BG values from Loop and Apple Health in the app's graphs. It also ensures that manual BG check entries from Nightscout using mmol are correctly shown. Additionally, the PR standardizes mmol/L <-> mg/dL conversions throughout the application using centralized constants for improved consistency and maintainability.
>  Implement Display of Manual BG Values and Standardize Unit Conversion

- LoopFollow/ViewControllers/SettingsViewController.swift
This PR addresses an issue where URLs copied and pasted into LoopFollow could fail due to extraneous characters like tabs, spaces or newlines. Changes include:
Implementing a regex-based filter to remove any non-URL appropriate characters.
Ensuring all URLs are processed to lowercase.
Impact:
These updates improve URL handling robustness, ensuring copied URLs function identically to manually entered ones, thus enhancing user experience and reducing errors.
> Sanitize and validate URL input to remove unwanted characters.

- LoopFollow/Controllers/Alarms.swift
Replace commas with periods in speech output to ensure clarity for users with commas as decimal separators, since commas are interpreted as pauses rather than spoken.
> Replace commas with periods in speech output

- LoopFollow/ViewControllers/SettingsViewController.swift
This PR enhances the `SettingsViewController` by allowing users to paste a URL that includes a token, automatically populating both the URL and token fields. This improvement aims to streamline the testing process.
1. **New functionality:**  
- Added support for handling URLs with embedded tokens.
- Automatically extracts and populates the token if found.
- Cleans up the URL accordingly.
2. **Code refactoring:**  
- Improved URL filtering and normalization logic.
- Removed redundant code and improved formatting.
1. **Manual Testing:**  
- Verified that pasting a URL with a token correctly populates the fields.
- Ensured that normal URL input behavior remains unchanged.
2. **Automated Testing:**  
- Added relevant unit tests for the new functionality.
This update primarily facilitates …
> Add support for pasting URL with token to populate both fields

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/ViewControllers/SettingsViewController.swift
- LoopFollow/helpers/AppVersionManager.swift
- LoopFollow/helpers/BuildDetails.swift
- LoopFollow/helpers/DateTime.swift
- LoopFollow/helpers/GitHubService.swift
- LoopFollow/repository/UserDefaults.swift
- Scripts/capture-build-details.sh
- blacklisted-versions.json
Using a blacklisted version
Update available
Using the current version
For testing, modify LOOP_FOLLOW_MARKETING_VERSION and url(s) in . GitHubService.
Results are cached for 24 hours, to always use new data, comment out row 24..28 in AppVersionManager
> Display branch, build date, latest version, blacklisted version

- LoopFollow/Application/AppDelegate.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/helpers/AppVersionManager.swift
- LoopFollow/helpers/BuildDetails.swift
- LoopFollow/helpers/GitHubService.swift
- LoopFollow/repository/UserDefaults.swift
This pull request introduces improved notifications for version updates, blacklisting, and build expiration, aiming to enhance user experience by keeping them informed about essential updates and app validity.
Version and Blacklist Notifications:
The application now checks for new versions and blacklisting status each time it becomes active. Notifications for new versions are shown biweekly, while blacklist notifications are shown daily if applicable.
Utilizes caching to reduce network calls. Cache validity is tied to the app version, ensuring data relevance.
Build Expiration Notification:
Alerts users if the app will expire within a week, with daily notifications to prompt action.
Useful for TestFlight builds or other distributions with set expiration dates.
Caching Enhancements: …
> Notification of new version, blacklisted version and build expiration

- LoopFollow/Controllers/Timers.swift
- LoopFollow/ViewControllers/AlarmViewController.swift
- LoopFollow/ViewControllers/GraphSettingsViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/ViewControllers/SettingsViewController.swift
- LoopFollow/ViewControllers/WatchSettingsViewController.swift
- LoopFollow/repository/UserDefaults.swift
In an effort to simplify the functionality and improve user experience, we have made a small update to the LoopFollow app. Previously, users had to manually toggle the option to download Nightscout data, dependent on a separate 'Download Loop/iAPS Data' setting. This has been streamlined to enhance efficiency and ease of use.
**Key Change:**
Automatic Data Download: The toggle for 'Download Loop/iAPS Data' has been removed. Now, the app will automatically start downloading Nightscout data whenever a URL is entered. This change ensures that users won't need to manage additional settings to start receiving data, reducing setup complexity and potential user errors.
This update is part of our ongoing efforts to make LoopFollow more intuitive and user-friendly, ensuring that your focus can …
> Remove Download Loop/iAPS Data toggle

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Application/AppDelegate.swift
- LoopFollow/Controllers/BackgroundAlertManager.swift
- LoopFollow/Controllers/Timers.swift
- LoopFollow/ViewControllers/MainViewController.swift
Shows an alert if the app hasn't been active for 6 minutes in background mode. BG is checked at least every 5 minutes.
> Alert if the app is not active in the background

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Controllers/Graphs.swift
- LoopFollow/Controllers/NightScout.swift
- LoopFollow/Controllers/Nightscout/Treatments.swift
- LoopFollow/Controllers/Nightscout/Treatments/SMB.swift
- LoopFollow/ViewControllers/MainViewController.swift
SMB's are now displayed with a light blue dot.
> Differentiating the display of SMBs from Manual boluses.

- LoopFollow/Controllers/Graphs.swift
- LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
- LoopFollow/Controllers/Nightscout/Treatments/Carbs.swift
- LoopFollow/ViewControllers/MainViewController.swift
An attempt to solve https://github.com/loopandlearn/LoopFollow/issues/121
> Reset topbg for each cycle

- LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/repository/UserDefaults.swift
> Show the eventually value and loopstatus

- Gemfile.lock
Some Fastlane error were reported in iAPS.
These could be solved by updating Fastlane to 2.221.1
In order to prevent errors happening with LoopFollow, go on and update it to Fastlane 2.221.1.
> Update Fastlane to 2.221.1

- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
**1.	DeviceStatus.swift:**
•	Corrected the count parameter for device status downloads from 288 to 1, as only one record is needed. The initial value was a copy-paste error, which led to unnecessary data being downloaded.
**2.	BGData.swift:**
•	Adjusted the count parameter to dynamically calculate the limit of BG values to download. The new formula accounts for both Loop/Trio and Dexcom Share data, leading to 2 * 288 BG values per day.
•	Previous hardcoded value: 1000. Two days of double data results in 1152 values.
•	New dynamic value: UserDefaultsRepository.downloadDays.value * 2 * 24 * 60 / 5
> Correct DeviceStatus Download Count and Dynamic BGData Download Limit

- LoopFollow.xcworkspace/xcshareddata/xcschemes/LoopFollow.xcscheme
Inspired by this PR to Loop
https://github.com/LoopKit/LoopWorkspace/pull/183
This PR resolves the logging initialization error when building to an iOS 17.5.1 device by adding the `IDEPreferLogStreaming` environment variable to the Launch and Profile actions in the LoopFollow scheme.
- **Added**: `IDEPreferLogStreaming=YES` to `.xcscheme` file.
- **Fixes**: Error message "Logging Error: Failed to initialize logging system. Log messages may be missing."
The initial error message is no longer seen in the Xcode debug log.
> Add IDEPreferLogStreaming env. variable to Launch and Profile actions

- LoopFollow/Info.plist
This PR updates the `Info.plist` to set `LSMinimumSystemVersion` to `13.0` to address the ITMS-90899 issue raised by Apple regarding macOS compatibility for Apple Silicon Macs.
Apple notifies that the app isn’t compatible with macOS 12.5 and needs to target macOS 13.0 or later. This change ensures compliance and resolves the warning during builds.
This update should prevent further warnings related to macOS version compatibility in future builds.
> Set LSMinimumSystemVersion resolve macOS compatibility issue

- LoopFollow/Controllers/Nightscout/BGData.swift
A small fix to filter out cal type entries from the bg result from Nightscout.
These entries would stop the bg value to be visible until they are out of scope for the fetch of data from Nightscout.
Preferably we should in the code filter out any type we don't want to use but this is what I have bandwidth to do right now.
> Filter out cal entries

- LoopFollow/Controllers/Nightscout/NSProfile.swift
- LoopFollow/Controllers/Nightscout/ProfileManager.swift
**Summary of Changes:**
This Pull Request introduces two main changes:
1. **Use Units from the Profile Store Instead of the Top-Level Units**
- **Description:**
- The units used within the profile's store (`store.units`) can differ from the units specified at the main level (`profileData.units`) when using Loop.
- Since the units are primarily used for interpreting profile data (e.g., basal rates, carb ratios), it makes sense to prioritize the units specified within the profile store.
- This change modifies the code to use the units from the profile's default store (`store.units`) when loading profile data.
- **Implementation Details:**
- Updated the `loadProfile` function to source `self.units` from `store.units` instead of `profileData.units`.
- Added the `units` property to the …
> Unit and timezone handling

- LoopFollow/Helpers/TextFieldWithToolBar.swift
- LoopFollow/Remote/TRC/MealView.swift
Before, the last valid value was used for the meal entry. Now the invalid value is cleared and the error message is displayed correctly.
> Align Carb and Bolus Guardrail Behavior

- LoopFollow/Remote/TRC/MealView.swift
With this change, a authentication is required for bolusing with meals. When there is no bolus, no auth is required.
> Require auth for meal bolus

- LoopFollow/Remote/TRC/MealView.swift
Adding a clarification about sheduling meal and bolus.
> Clarification about scheduled meal and bolus

- LoopFollow/Remote/TRC/MealView.swift
Use seconds from current time when scheduling meals. This is a trick to avoid Nightscout to overwrite meals scheduled at the same time.
> Meal seconds from current time

- LoopFollow/Helpers/TextFieldWithToolBar.swift
- LoopFollow/Remote/TRC/TempTargetView.swift
- LoopFollow/Remote/TrioNightscoutRemoteView.swift
This PR aligns the temp target guardrails with trio 80-200 (4,5-11,1).
> Align temp target guardrails with Trio

- LoopFollow/Remote/Settings/RemoteSettingsView.swift
Added information about device token, production env, team id and bundle id in the bottom of the Remote/TRC screen.
I verified that switching build method for Trio changes the production env boolean without restarting LoopFollow. Please note, the production env bool is in the profile and the profile information is refreshed every 10 minutes.
> TRC debug info

- LoopFollow/Controllers/Graphs.swift
Fix a crash that occurred when wrapping very long words by ensuring the substring length is never negative. This change adjusts the calculation of availableSpace and adds checks to prevent out-of-bound string indexing, stabilizing text wrapping behavior.
> Fix crash for long lines without spaces

- LoopFollow/Controllers/Nightscout/Treatments/Basals.swift
This PR addresses a crash caused by force unwrapping during the casting of ‘duration’. The casting is now handled safely using optional binding to prevent runtime errors.
> Fix crash by safely handling optional casting for ‘duration’

- LoopFollow/Controllers/Nightscout/Treatments/Basals.swift
- LoopFollow/Controllers/Nightscout/Treatments/Carbs.swift
- LoopFollow/Helpers/NightscoutUtils.swift
Updated date parsing for basals using a new helper function supporting both Trio and Loop date formats.
> Fix date parsing for Temp Basals using ISO8601DateFormatter

- LoopFollow/Controllers/Alarms.swift
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/ViewControllers/MainViewController.swift
Solves https://github.com/loopandlearn/LoopFollow/issues/320
The ‘+’ sign was missing in notifications, fixed in this PR.
> Bugfix, show delta string with +- sign in notifications

- LoopFollow/Controllers/Nightscout/Treatments/Overrides.swift
- LoopFollow/Task/TaskScheduler.swift
Solves https://github.com/loopandlearn/LoopFollow/issues/354
This PR limits displayed override duration to 'Hours of Prediction' after current time.
> Limit displayed override duration to 'Hours of Prediction' after current time

- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
- LoopFollow/Controllers/Nightscout/DeviceStatusLoop.swift
- LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
- LoopFollow/Storage/Observable.swift
- LoopFollow/ViewControllers/MainViewController.swift
Trio 1.0 now always uploads both suggested and enacted data, whereas before, only suggested was uploaded if new data was available after an enacted entry.
Adjusted how device status is fetched, ensuring it correctly handles both suggested and enacted data, where data in suggested is prioritized and last loop date is fetched from enacted's timestamp.
> Adapt LoopFollow to Trio 1.0’s Updated Device Status Upload Behavior

- LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
Fix for a bug introduced in v2.2.9.
This restores proper display of predictions for released version of Trio, Trio 0.2.3 and earlier.
See Issue #371 for details.
> Predictions for released version of Trio

- LoopFollow/Controllers/Alarms.swift
- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
- LoopFollow/Helpers/DataStructs.swift
- LoopFollow/Storage/UserDefaults.swift
- LoopFollow/ViewControllers/AlarmViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
- LoopFollow/ViewControllers/SnoozeViewController.swift
This change adds the ability to setup a battery drop alarm for situations where the battery is being consumed rapidly.
The specific use-case we ran into was based on the camera app being left opened and draining the battery rapidly without the operator knowing it was happening.
The user can setup the battery drop percentage and period of time to monitor the drop.  The implementation uses a fuzzy match to find the closest battery reading to the defined period to account for differences in polling for the battery data.
**User configured values**
- Battery Drop is between 5 - 100%
- Period (minutes) is between 5 -30 minutes
- Snooze is defined in hours
The change will store a maximum of 30 battery updates.  Which can cover anywhere from around 30 minutes to 2.5 hours depending on polling. …
> Add battery drop alarm

- LoopFollow/Contact/ContactImageUpdater.swift
- LoopFollow/Contact/Settings/ContactSettingsView.swift
- LoopFollow/Contact/Settings/ContactSettingsViewModel.swift
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/Storage/ObservableUserDefaults.swift
- LoopFollow/Storage/UserDefaults.swift
Added a color selector in the Contact settings so individuals can choose different colors based on their watch faces and their preferences.  Also should allow individuals with multiple loopers to be able to assign a different color to each.  I have tested this on my phone and watch but before merging into the main branch, this new code will benefit from additional code review and/or testing.  Thank you!
> Color selection for Contact Image

- LoopFollow/Controllers/BackgroundAlertManager.swift
- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
- LoopFollow/Task/TaskScheduler.swift
- **Throttled Scheduling:**  
Background refresh notifications are now re-scheduled at most once every 10 seconds, preventing intensive calls to this functionality.
- **Device Status Retry:**  
When device status returns empty, the system now retries after 5 minutes instead of giving up immediately.
- **Alarm Check Delay:**  
Alarm check tasks now wait 5 seconds after `.deviceStatus`, `.treatments`, and `.fetchBG` are complete before re-attempting, avoiding immediate re-triggers.
> Task improvements

- .github/workflows/add_identifiers.yml
- .github/workflows/build_LoopFollow.yml
- .github/workflows/create_certs.yml
- .github/workflows/validate_secrets.yml
- fastlane/Fastfile
- fastlane/testflight.md
This PR provides the capability (found in Trio 0.2.3) to:
1. Check for updates to default branch every Wed
* If updates are available, sync the branch and build
* Otherwise, skip the build
2. Build on the first of each month
* This includes a sync of the branch if needed
* The build happens regardless to ensure a TestFlight build is always available (assuming license agreements are signed and account is valid)
3. Add the ability to check Certificates and if necessary, Nuke the certs and create new ones
* This requires the addition of an Environment variable (to organization or repo) of ENABLE_NUKE_CERTS
* This replaces the manual instructions in LoopDocs on how-to Renew Certificates
* Once secrets are added and identifiers provided for the app, only the build action is required
4. This …
> Auto update and build LoopFollow on schedule, auto renew certificates

- LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
**Summary**
This PR updates the threshold for dynamically detecting the ISF (Insulin Sensitivity Factor) unit from 15 to 16.
**Background**
ISF does not always use the unit from the profile. If there is an override affecting ISF, it is reported in mg/dL/unit instead of the profile’s default unit.
**Change Details**
•	Previously, ISF values up to 15 were detected as mmol/L/unit (≈ 0.83 mmol/L/unit).
•	With this change, ISF values up to 16 will now be detected as mmol/L/unit (≈ 0.89 mmol/L/unit).
**Rationale**
This adjustment allows for slightly higher ISF values to still be interpreted as mmol/L/unit.
> Adjust ISF Unit Detection Threshold from 15 to 16

- LoopFollow/Helpers/BuildDetails.swift
- LoopFollow/Log/LogManager.swift
- LoopFollow/ViewControllers/SettingsViewController.swift
Enhanced the logging to include detailed build information. When the app starts and for when a new log file is created it now logs the app version, build date, branch info, and, if not running on a Mac or Simulator, the expiration date.
> Log app version and build details

- LoopFollow/Log/LogManager.swift
Task scheduler does write a lot to the debug log, this change ignores those log rows attempts - they are still visible in the debug console when debugging from xcode. We might want to add a toggle for it in the future.
> Skip task scheduler logging

- LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
Sometimes an old enacted is uploaded, older than the previous one. This check ignores the enacted timestamp update if it is older than the last one on record.
> Ignore old enacted timestamps

- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
This PR adds an charging indicator for when the looping phone is charging. This has been tested with Trio, this feature could be included in Loop in the future as well.
Thanks to @dsnallfot for informing me that this information is available in Trio device status.
> Display charging indicator

- .github/workflows/build_LoopFollow.yml
The `gautamkrishnar/keepalive-workflow` has been taken down by GitHub. ~~We do not know if this is permanent or not.~~ We now know this is a permanent change.
This PR makes a minimal change to the current build_LoopFollow.yml which renables building with GitHub actions.
Comment out the section that is not available and insert an echo for the log file.
At a later time, the whole logic thread for automatic build will be reviewed, updated and documented.
This was copied from the LoopWorkspace change and requires test.
> disable keepalive-workflow because the repo is no longer available

- LoopFollow/Extensions/ShareClientExtension.swift
This PR fixes a crash in `ShareClient.fetchData` that occurred when the `fetchLast` method returned both `error == nil` and `result == nil`. The original guard clause allowed this case to pass, leading to a force unwrap on `result!`, which caused a runtime crash (`EXC_BREAKPOINT` / `SIGTRAP`).
- Updated the guard clause in `fetchData` to only proceed when both `error == nil` and `result != nil`.
- Replaced force-unwraps of `result![i]` with direct usage of the loop variable `item` for safer and cleaner code.
This change prevents crashes when Dexcom Share responds with an unexpected empty payload or malformed data, ensuring the app gracefully handles and logs the error instead.
> Fix crash when ShareClient returns nil result without error

- LoopFollow/Controllers/Nightscout/BGData.swift
`dexShare?.fetchData()` could return an empty array even when the network call succeeds.  
Our previous guard only checked for `nil`, so subscripting `data[0]` would crash with “index out of range”.
* Extend the guard clause to `guard let data = result, !data.isEmpty`  
* Update the log message to “Received empty data array from Dexcom” for clarity.
1. Point the Dexcom share stub/service at a response that returns `[]`.
2. Launch the app and trigger a download.
3. Verify:
* No crash occurs.  
* Log output shows the new message.  
* The fallback to `webLoadNSBGData()` is executed.
No functional changes beyond the safety check.
> Dexcom empty data guard

- LoopFollow/Controllers/Nightscout/Treatments.swift
Adds support for displaying insulin treatments with event type "External Insulin", enabling LoopFollow to show externally injected insulin alongside manual boluses.
> Support for Trio External Insulin Display

- release.sh
After using the release.sh for the first time, decide to add some more comments at the pauses and update some of the comments that are already there.
> Add more comments at pauses for release.sh [ci skip]

- LoopFollow/Nightscout/NightscoutSettingsView.swift
- LoopFollow/Settings/DexcomSettingsView.swift
**Closes #417**
This pull request addresses the issue of sensitive credentials (Dexcom password and Nightscout token) being displayed in plain text in the settings views. To enhance security and user privacy, the standard `TextField` has been replaced with the existing `TogglableSecureInput` component for these fields.
1.  **`DexcomSettingsView.swift`**:
* Replaced the `TextField` for the password with `TogglableSecureInput`.
* Wrapped the "User Name" and "Password" rows in `HStack`s for consistent UI alignment.
2.  **`NightscoutSettingsView.swift`**:
* Replaced the `TextField` for the "Access Token" with `TogglableSecureInput`.
* Updated the layout to use an `HStack` for better alignment of the label and the input field.
* Changed the label from "Token" to "Access Token" for clarity.
* …
> Implement Secure Inputs for Dexcom and Nightscout Credentials

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Alarm/AlarmsContainerView.swift
- LoopFollow/ViewControllers/AlarmViewController.swift
- LoopFollow/ViewControllers/MainViewController.swift
This PR introduces a dynamic second tab in the tab bar. 🛠️
For users who have remote functionality **enabled** (i.e., `remoteType` is not `.none`), the second tab will continue to show the **Remote** view.
For users who do **not** use the remote features (`remoteType` is `.none`), this change restores the **Alarms** view to the second tab. This provides these users with quick and convenient access to alarm configuration without having to navigate through the settings menu.
This implementation listens for changes to the `remoteType` setting and updates the tab bar in real-time.
> Make Second Tab Configurable

- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
This pull request resolves issue #403.
**Description:**
This change introduces a conditional clearing of the override information in the `infoManager`. Previously, the override data was cleared every time the device status was updated.
This caused an issue for Trio users, where the override text would disappear from the display. This happened because for Trio, override information is fetched from treatments, and the device status does not contain this data. If a device status update occurred after the treatment data was processed, the override information would be incorrectly cleared.
For "Loop" devices, the override information *is* part of the device status, so clearing it upon refresh is the correct behavior to ensure the display is up-to-date.
**Changes:**
- In …
> Clear override text conditionally based on device

- LoopFollow/Alarm/AlarmCondition/NotLoopingCondition.swift
- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
- LoopFollow/Storage/Storage.swift
This pull request resolves issue #422 by preventing the "Not Looping" alarm from firing when the app itself has not been able to recently check for a new status from Nightscout.
The "Not Looping" alert could persist incorrectly if the app hasn't been active for a while, since the `lastLoopTime` was not being updated, it would trigger the "Not Looping" alarm, even though the issue was that the app did not fetch the data, not the loop itself.
To fix this, I've introduced a new timestamp, `lastLoopingChecked`, which is updated every time the app *attempts* to fetch the device status.
The `NotLoopingCondition` now includes a new safeguard:
1.  It checks when the last status fetch was *initiated*.
2.  If the last check attempt is more than 6 minutes old, the alarm condition is ignored.
This …
> Prevent stale "Not Looping" alarms

- LoopFollow/Alarm/AlarmManager.swift
This PR fixes a bug where the **"Snooze All"** setting was not being honored. Alarms would continue to trigger even after the global snooze was activated from the settings screen.
The `checkAlarms` function now correctly checks for the global `snoozeUntil` configuration at the very beginning. If snoozing is active, it will stop any current alarm and exit immediately, ensuring no new alarms are triggered until the snooze period is over.
A big thank you to **Daniel Mini Johansson** for reporting this issue! ✨
> Fix: Honor the global "Snooze All" setting

- LoopFollow/Settings/SettingsMenuView.swift
- LoopFollow/Storage/Observable.swift
- LoopFollow/ViewControllers/SettingsViewController.swift
**Problem**: When switching between tabs and returning to Settings, the navigation stack remained at the last viewed screen instead of returning to the root settings menu.
**Solution**: 
- Added `settingsPath` to the shared `Observable` class to manage settings navigation state
- Updated `SettingsMenuView` to use the centralized navigation path
- Reset navigation path in `SettingsViewController.viewWillAppear()` to ensure users always return to the root settings screen
**Benefits**:
- Consistent user experience when switching tabs
- Follows existing app architecture patterns
- Centralized navigation state management
> Reset Settings Navigation on Tab Switch

- LoopFollow/Remote/RemoteViewController.swift
Improves the RemoteViewController's update mechanism by optimizing unnecessary subscriptions and ensuring the view refreshes when the tab is selected.
- **Removed** subscription to `Storage.shared.remoteType.$value` - since remote type changes only happen in the settings tab, this view will now naturally re-render when switching back to the remote tab
- **Kept** subscription to `Storage.shared.device.$value` - device changes can affect the current view and should trigger updates
- **Simplified** from `CombineLatest` to single publisher subscription
- **Added** `viewWillAppear(_:)` override to call `updateView()` when the tab is selected
- **Removed** `updateView()` call from `viewDidLoad()` to avoid redundant initial render
- **Removed** unused imports (`Foundation`, `HealthKit`)
- …
> Optimize RemoteViewController updates and refresh view on tab selection

- LoopFollow/Helpers/Views/TogglableSecureInput.swift
- LoopFollow/Nightscout/NightscoutSettingsView.swift
When users select and delete the Nightscout URL, they have to navigate back to settings and return to the NS URL view before the password autofill feature works again for the token field.
- Added `textContentType` parameter to `TogglableSecureInput` component
- Set `textContentType: .password` for the Nightscout token field
- This properly identifies the field to iOS's autofill system, maintaining consistent behavior even after URL changes
- Modified `TogglableSecureInput.swift` to accept optional `textContentType` parameter
- Updated `NightscoutSettingsView.swift` to specify `.password` content type for token field
- Applied content type to both secure and visible states of the input
- Verified that password autofill now works consistently after URL deletion
- Confirmed no regression in …
> Fix Nightscout token autofill by adding textContentType

- LoopFollow/Alarm/AlarmCondition/RecBolusCondition.swift
- LoopFollow/Alarm/AlarmManager.swift
- LoopFollow/Controllers/Nightscout/BGData.swift
- LoopFollow/Controllers/Nightscout/DeviceStatus.swift
- LoopFollow/Task/TaskScheduler.swift
- LoopFollow/Task/TreatmentsTask.swift
This pull request resolves an issue where `alarmCheck` was being executed excessively in rapid succession when multiple data sources refreshed simultaneously. It refactors the task scheduling logic to be more efficient and reliable by debouncing the calls.
1.  **Debounced `alarmCheck` Calls:**
- In `BGData.swift`, `DeviceStatus.swift`, and `TreatmentsTask.swift`, the call to reschedule `alarmCheck` is now delayed by 3 seconds (`.addingTimeInterval(3)`).
- This ensures that if multiple data refreshes occur in a short window, `alarmCheck` only runs once after the final update, preventing redundant executions.
2.  **Simplified `TaskScheduler`:**
- The previous complex logic to manually skip `alarmCheck` has been removed from `TaskScheduler.swift`.
- This logic is now obsolete due to the …
> Debounce alarm checks and improve scheduling logic

- LoopFollow/ViewControllers/NightScoutViewController.swift
Closes #154.
This PR introduces two improvements to the `NightscoutViewController`:
* **Enables Pinch-to-Zoom:** The Nightscout page disables user scaling via its viewport `<meta>` tag. This change injects a small JavaScript snippet after the page loads to override this setting (`user-scalable=0`), allowing users to pinch-to-zoom on the graph as requested in the issue.
* **Fixes Deprecation Warning:** Updates the code to resolve a warning for `javaScriptEnabled`, which was deprecated in iOS 14. It now uses the modern `WKWebpagePreferences` API to enable JavaScript, improving code health and future compatibility.
1.  Navigate to the Nightscout view in the app.
2.  Verify that you can now pinch-to-zoom on the web content.
3.  Confirm the project builds without warnings related to …
> Fixes #154: Enable zoom in Nightscout view

- LoopFollow/Snoozer/SnoozerView.swift
This PR introduces several enhancements to the Snoozer view to improve at-a-glance readability and provide better user context, addressing Issue #440 .
**Key Changes:**
* **Larger BG Text:** The font size and frame for the BG value have been increased, making it the primary focal point of the view.
* **Optional Display Name:** The app's display name can now be shown in the `rightColumn`, which works well in both portrait and landscape modes. This is controlled by the `showDisplayName` setting.
* **Adaptive Landscape Layout:** In landscape mode, the trend arrow and delta value are now displayed side-by-side for a more compact and readable layout.
> Enlarge BG text and add optional display name

- LoopFollow/Snoozer/SnoozerView.swift
Improves the visibility and usability of the snooze button in SnoozerView for better accessibility, especially for users without glasses in dark conditions.
- Increased button height from 50pt to 80pt for easier tapping
- Changed button color from accent color (blue) to orange for better visibility
- Increased font size to 30pt for improved readability
- Changed button shape from rounded rectangle to capsule for modern Apple design aesthetic
- Maintained white text color for optimal contrast
The snooze button needs to be highly visible and easy to tap during nighttime alarm scenarios. The orange color provides better contrast against the black background while maintaining Apple's design language for time-sensitive actions.
> feat: Enhance snooze button visibility with larger size and orange color

- .github/workflows/build_LoopFollow.yml
The Browser Build for LoopFollow began to fail about 14 August 2025, after previously succeeding.
By modifying the explicit version request from Xcode_16.2 to Xcode_16.4, the builds began working again.
At this time, we tested several options and determined the best approach is to explicitly specify the highest minor version that works correctly.
| Explicit Request | Result |
|:--|:-:|
| Xcode 16.2 | fail |
| Xcode 16.3 | succeed |
| Xcode 16.4 | succeed |
| Xcode 16 | fail |
> Update to Xcode 16.4

- LoopFollow/Alarm/AlarmCondition/MissedReadingCondition.swift
- LoopFollow/Alarm/AlarmManager.swift
This PR fixes a bug where the Missed Reading alert would not trigger when CGM data became stale.
The alert was being blocked by a global check that required all `isBGBased` alarms to have *recent* BG data. This directly conflicted with the purpose of the Missed Reading alert.
-   The alarm remains classified as `isBGBased` to correctly use the system's debounce logic (`lastBGAlarmTime`).
-   A targeted exception, `alarm.type != .missedReading`, is added to the "recent data" check, allowing the alarm to fire as intended.
-   The condition logic is also updated to use the correct `now` timestamp for consistency.
> Fix(alarm): Correct logic for missed reading alert

- LoopFollow.xcodeproj/project.pbxproj
- LoopFollow/Remote/LoopAPNS/LoopAPNSBolusView.swift
- LoopFollow/Remote/LoopAPNS/LoopAPNSCarbsView.swift
- LoopFollow/Remote/LoopAPNS/TOTPService.swift
- LoopFollow/Storage/Observable.swift
- LoopFollow/Storage/Storage.swift
This commit implements a security enhancement to prevent the reuse of Time-based One-Time Password (TOTP) codes when sending Loop commands via APNS (Apple Push Notification Service). The change ensures that each TOTP code can only be used once within its 30-second validity period.
1. New Storage Properties (Storage.swift)
Added loopAPNSTOTPUsed: Boolean flag to track if a TOTP code has been used
Added loopAPNSTOTPLastUsed: Timestamp tracking when the TOTP was last used
2. Enhanced TOTP Validation Logic
Bolus View (LoopAPNSBolusView.swift): Added isTOTPBlocked computed property
Carbs View (LoopAPNSCarbsView.swift): Added identical isTOTPBlocked computed property
Both views now check TOTP usage status before allowing command submission
3. UI Enhancements
Warning Display: Added visual …
> Block sending loop commands with same TOTP code

- LoopFollow/Helpers/Views/TogglableSecureInput.swift
Changes behaviour of inputs in screenshots. 
Instead of making them invisible, they shows up as masking dots.
> Change input fields to be masked instead of invisible in screenshots

- LoopFollow/Remote/LoopAPNS/OverridePresetsView.swift
This PR enhances the Loop APNS override functionality by replacing the simple confirmation alert with an interactive modal that allows users to configure override duration settings before activation.
* Override Duration Modal: Replaces basic confirmation dialog with a comprehensive modal for override configuration
* Duration Control: Added slider for setting custom override duration (15 minutes to 24+ hours)
* Indefinite Override Toggle: Added toggle to enable/disable indefinite overrides
* Smart Duration Display: Duration slider shows time in intuitive hours and minutes format (e.g., "1h 30m")
* Preset Information Display: Modal shows override details including symbol, name, target range, and insulin needs
* Contextual Warnings: Displays warning for overrides with default durations that …
> Add modal for selecting duration of overrides for Loop

- .github/workflows/build_LoopFollow.yml
Try to avoid times when GitHub actions are historically busy.
Thanks Carol Vachon for this report:
> The most significant and consistent historic pattern impacting GitHub activity is the week-to-weekend cycle, as most development work happens during the standard workweek.
> * Lowest activity: Weekends, especially Sundays, see the least amount of activity, as most developers are off work.
> * Highest activity: Activity is typically at its peak from Tuesday to Thursday.
> * Moderate activity: Mondays and Fridays have moderate activity as developers ease into and out of the workweek.
On Wed, Oct 1, GitHub actions were impacted and all builds across the Open Source community all failed.
* Shift the weekly build in case of code updates from Wednesday to Sunday
* Shift the monthly builds, …
> Shift GitHub to check for updates every Sunday and build 2nd Saturday of each month
