loopandlearn/LoopFollow

LoopFollow/Controllers/Alarms.swift, LoopFollow/Controllers/Graphs.swift, LoopFollow/Controllers/NightScout.swift, LoopFollow/ViewControllers/MainViewController.swift, LoopFollow/ViewControllers/SettingsViewController.swift, LoopFollow/repository/UserDefaults.swift
Reverts jonfawcett/LoopFollow#30
=> Revert "Dev Merge"

LoopFollow/Extensions/ShareClientExtension.swift, LoopFollow/ViewControllers/MainViewController.swift
I had to fix some omissions/typos to the trend table and added check for nil for debug of pulling share data
=> Fix to Dexcom PR

LoopFollow.xcodeproj/project.pbxproj, LoopFollow/Application/AppDelegate.swift, LoopFollow/Application/SceneDelegate.swift, LoopFollow/Controllers/AppStateController.swift, LoopFollow/Controllers/Graphs.swift, LoopFollow/Controllers/NightScout.swift, LoopFollow/Extensions/UIViewExtension.swift, LoopFollow/ViewControllers/AlarmViewController.swift, LoopFollow/ViewControllers/AppStateViewController.swift, LoopFollow/ViewControllers/DebugSettingsViewController.swift, LoopFollow/ViewControllers/DebugViewController.swift, LoopFollow/ViewControllers/GeneralSettingsViewController.swift, LoopFollow/ViewControllers/GraphSettingsViewController.swift, LoopFollow/ViewControllers/InfoDisplaySettingsViewController.swift, LoopFollow/ViewControllers/MainViewController.swift, LoopFollow/ViewControllers/NightScoutViewController.swift, LoopFollow/ViewControllers/SettingsViewController.swift, LoopFollow/ViewControllers/SnoozeViewController.swift, LoopFollow/ViewControllers/WatchSettingsViewController.swift, LoopFollow/repository/UserDefaults.swift
This merges all jp changes with jf changes
=> Merge All Latest Changes

LoopFollow/Controllers/Stats.swift
Convert the standard deviation to mmol/L when output units are set to mmol/L in settings.
=> Output standard deviation in mmol/L when required

LoopFollow/ViewControllers/GeneralSettingsViewController.swift
=> Keep Screen Active reverts back ON if turned OFF #105

.github/workflows/add_identifiers.yml, .github/workflows/build_LoopFollow.yml, .github/workflows/create_certs.yml, .github/workflows/validate_secrets.yml, fastlane/Fastfile, fastlane/testflight.md
Updates to Fastlane builds based on https://github.com/LoopKit/LoopWorkspace/pull/36
> Validate repository secrets (https://github.com/LoopKit/LoopWorkspace/pull/36)
> * Validate repository secrets
> 
> Adds support for validation of repository secrets.
> 
> * Validate $FASTLANE_KEY as unencrypted PKCS#8
> 
> * Number workflows to guide sequential exection
=> Update Github Actions and Fastlane

readme.md
=> Add Home Screen Quick Action for Speak BG

LoopFollow/Controllers/NightScout.swift, LoopFollow/Controllers/Timers.swift, LoopFollow/ViewControllers/MainViewController.swift, LoopFollow/repository/UserDefaults.swift
This pr adds a new item to the 'Information Table' called 'Carbs Today.' This feature provides a sum of all registered carbs since midnight to help you keep track of your child's carb intake for the day. However, please note that this feature may not be useful if you are using fake carbs.
=> Carbs Today

LoopFollow.xcodeproj/project.pbxproj, LoopFollow/Controllers/NightScout.swift, LoopFollow/Controllers/Timers.swift, LoopFollow/ViewControllers/MainViewController.swift, LoopFollow/ViewControllers/SettingsViewController.swift, LoopFollow/helpers/NightscoutUtils.swift, LoopFollow/repository/UserDefaults.swift
Merge 3 PR after testing them individually in the dev branch.
* PR #186 
* PR #194
* PR #195
=> Upgrades for LoopFollow

LoopFollow/Controllers/AppStateController.swift, LoopFollow/Controllers/Graphs.swift, LoopFollow/ViewControllers/GraphSettingsViewController.swift, LoopFollow/repository/UserDefaults.swift, readme.md
A blue line is added 30 minutes prior to the current time to provide a clearer view of the boluses that have started to take effect. I described it in this issue, resulted in some modifications but not the blue line. https://github.com/jonfawcett/LoopFollow/issues/110
=> Blue Bolus Line -30 minutes and Protein Line -90 minutes

LoopFollow/Controllers/NightScout.swift
=> Treat smb as bolus

LoopFollow/Controllers/Nightscout/DeviceStatus.swift
Do not report fraction digits for COB in the Info Display, as that makes no sense.
Originally suggested by @aug0211, not sure if it was made into a PR before.
=> No fraction digits for COB

.github/workflows/add_identifiers.yml, .github/workflows/build_LoopFollow.yml, .github/workflows/create_certs.yml, .github/workflows/validate_secrets.yml
Bumping dependencies for browser build, see LoopKit/LoopWorkspace#120 for detailed description.
=> Bump browser build dependencies to Node 20

.github/workflows/add_identifiers.yml, .github/workflows/build_LoopFollow.yml, .github/workflows/create_certs.yml
Updated the build system to use Xcode 15 and iOS 17 SDK to meet the latest App Store requirements.
=> Update to Xcode 15 and iOS 17 SDK for App Store compliance

LoopFollow/Controllers/Alarms.swift, LoopFollow/Controllers/Nightscout/DeviceStatus.swift, LoopFollow/ViewControllers/AlarmViewController.swift, LoopFollow/ViewControllers/SnoozeViewController.swift, LoopFollow/repository/UserDefaults.swift
Resolves: https://github.com/loopandlearn/LoopFollow/issues/284
=> Add recommended bolus alert

LoopFollow/Extensions/ShareClientExtension.swift
Adding glucose as a allowed key for bg values.
=> Allow bg entries as glucose

LoopFollow/Controllers/Nightscout/BGData.swift, LoopFollow/Controllers/Nightscout/DeviceStatus.swift, LoopFollow/ViewControllers/MainViewController.swift, LoopFollow/ViewControllers/SettingsViewController.swift, LoopFollow/helpers/Globals.swift
let data = result!
and
let latestDate = data[0].date
Would crash if data is nil when error is nil, I did refactor the code to avoid a potential crash here in response to: https://github.com/loopandlearn/LoopFollow/issues/303
Also found some dead code that is now removed.
=> Hardened dexcom share and removed dead code

.github/workflows/add_identifiers.yml, .github/workflows/build_LoopFollow.yml, .github/workflows/create_certs.yml, .github/workflows/validate_secrets.yml
Update all runners to use macOS 14
Update the explicit Xcode version to 15.4
=> update runners to macOS 14 in yml files

Gemfile, Gemfile.lock
=> Rexml update

LoopFollow.xcodeproj/project.pbxproj, LoopFollow/Contact/ContactImageUpdater.swift, LoopFollow/Contact/Settings/ContactSettingsView.swift, LoopFollow/Contact/Settings/ContactSettingsViewModel.swift, LoopFollow/Controllers/ContactImageUpdater.swift, LoopFollow/Controllers/Graphs.swift, LoopFollow/Controllers/Nightscout/BGData.swift, LoopFollow/Info.plist, LoopFollow/Storage/ObservableUserDefaults.swift, LoopFollow/ViewControllers/MainViewController.swift, LoopFollow/ViewControllers/SettingsViewController.swift
LoopFollow contact image with bg info, intended for apple watch - just add the LoopFollow - BG contact to the watch face to follow the bg value in real time.
* Options for delta value or arrow
* Dynamic font size
* Contact name is based upon the app display name, making it possible to use three instances of LoopFollow showing three different bg values on the watch face.
=> Contact image with bg information

LoopFollow/Remote/Settings/RemoteSettingsView.swift
Adds a temporary modification making TRC only available when not building the Main branch.
=> Trio remote controll feature toggle

LoopFollow/Controllers/Nightscout/DeviceStatusOpenAPS.swift
With this change, the suggested record will be used instead of Fallback on suggested if enacted is not present if Fallback on suggested if enacted is not present is not present.
See discussion in discord/tcd-general.
=> Fallback on suggested if enacted is not present

LoopFollow/Storage/UserDefaults.swift, LoopFollow/ViewControllers/AlarmViewController.swift, LoopFollow/ViewControllers/MainViewController.swift
Solves https://github.com/loopandlearn/LoopFollow/issues/353
See the issue for an explanation of this change.
=> Alert missed reading stepvalue change

LoopFollow/Controllers/Alarms.swift, LoopFollow/Controllers/Nightscout/BGData.swift, LoopFollow/Controllers/Nightscout/DeviceStatus.swift, LoopFollow/Log/LogManager.swift
As discussed earlier, a separate PR for logging when an Alarm is triggered. I also did some cleanup of unused variables.
=> Add alarm log and some cleanup

LoopFollow/Task/TaskScheduler.swift
This PR enhances the thread safety of the Task Scheduler by replacing the main-thread `Timer` with a `DispatchSourceTimer`. All timer scheduling and task management now occur on a dedicated serial queue, eliminating potential data races even when public methods are invoked from arbitrary threads.
- **DispatchSourceTimer Implementation:**  
- Replace `Timer` with a `DispatchSourceTimer` scheduled on the Task Scheduler’s serial queue.
- **Safe Publication:**  
- Configure the timer in a local variable before assigning it to `currentTimer`, ensuring the timer is fully configured before exposure.
- **Thread Safety:**  
- Confine all accesses to shared state (`tasks` dictionary and `currentTimer`) to a single serial queue.
- **Refactoring:**  
- Minor code cleanup and improved logging for …
=> Task Scheduler Thread Safety Improvements

LoopFollow/Remote/Loop/LoopOverrideView.swift, LoopFollow/Remote/Nightscout/TrioNightscoutRemoteView.swift, LoopFollow/Remote/TRC/BolusView.swift, LoopFollow/Remote/TRC/MealView.swift, LoopFollow/Remote/TRC/OverrideView.swift, LoopFollow/Remote/TRC/TempTargetView.swift
Adds logging for remote commands.
Solves: https://github.com/loopandlearn/LoopFollow/issues/387
=> Add logging for remote commands
